# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0fe13f6c2ea691ea36f1510a9bd1c504ba4024489d13177cb9ab8e1990a847f51f4ef86748e2f185b065aa7b330b21243be109f5198a2fbae4b965c05a9ddf

test:
  secret_key_base: 8e5d8d5692c99eca035cf4520977b2eb414b6bd68e2adf3ede0da5dae9154bcbb34781216131daaf8b279ccb4d043f770d7371028b26ccb03d7be8f250b4e8fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
